### ISSUE TITLE
运行npm run dev抛Couldn't find preset "react" relative to directory 

### ISSUE THREAD

**Issue by klboke** [blockchain-jd-com/explorer#2]
运行npm run dev抛如下异常：
```
Module build failed: Error: Couldn't find preset "react" relative to directory "F:\\github\\explorer"
    at F:\github\explorer\data-explorer\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (F:\github\explorer\data-explorer\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (F:\github\explorer\data-explorer\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (F:\github\explorer\data-explorer\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (F:\github\explorer\data-explorer\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (F:\github\explorer\data-explorer\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (F:\github\explorer\data-explorer\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (F:\github\explorer\data-explorer\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (F:\github\explorer\data-explorer\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (F:\github\explorer\data-explorer\node_modules\babel-loader\lib\index.js:173:20)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8081 webpack/hot/dev-server react-hot-loader/patch ./app-web.js
```
说明：
已经正常执行npm install安装好所有的依赖，发现项目寻找node_modules的目录有问题，没有寻找当前目录下的node_modules而是跑到父目录去了。

临时解决：
目前将data-explorer模块下的package.json迁移到explorer根目录下，在explorer根目录下执行npm install安装好依赖，就没问题了

**Comment by zhaoGuangwei** [comment]
感谢凯玲的反馈。目前我们一般直接使用：mvn clean install的命令来执行，所以未感知到这个异常。我把您这个经验在常见问题中收录一下，方便其它用户参考。再次感谢！
